name: Schedule Tests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar o java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar o Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn test -Dtest=**/*RunCucumberTest -Dbrowser=chrome-ci "-Dcucumber.options= --tags ~@ignore"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formatedreport/'

# De preferência colocar os alertas desse teste em outro canal lá no Slack para que as notificações do PR
# não se misturem com as notificações do Schedule
      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://image.similarpng.com/very-thumbnail/2021/05/Checkmark-green-tick-isolated-on-transparent-background-PNG.png
          SLACK_TITLE: "Mensagem"
          SLACK_MESSAGE: "Sucesso na execução de testes AGENDADOS :white_check_mark: "
          SLACK_USERNAME: ">>>SUCESSO<<<"

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://icon-library.com/images/failed-icon/failed-icon-7.jpg
          SLACK_TITLE: "Mensagem"
          SLACK_MESSAGE: "Falha na execução de testes AGENDADOS :fire: "
          SLACK_USERNAME: ">>>FALHA<<<"