name: Schedule Tests

on:
  schedule:
    - cron: '50/5 * 11 FEB *'

jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar o java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar o Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn test -Dtest=**/*RunCucumberTest -Dbrowser=chrome-ci "-Dcucumber.options= --tags ~@ignore"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formatedreport/'