name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar o java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar o Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn clean test -Dtest=**/*RunCucumberTest -Dbrowser=chrome-ci "-Dcucumber.options= --tags @logoff-sucesso"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formatedreport/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: blob:https://web.whatsapp.com/1f8641c6-7423-4baa-8c3d-434651a93520
          SLACK_TITLE: "Mensagem"
          SLACK_MESSAGE: "Sucesso na execução de testes do PR :white_check_mark: "
          SLACK_USERNAME: ">>>SUCESSO<<<"

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: blob:https://web.whatsapp.com/53c03a90-e42f-4ea5-b559-747b115c28b8
          SLACK_TITLE: "Mensagem"
          SLACK_MESSAGE: "Falha na execução de testes do PR :fire: "
          SLACK_USERNAME: ">>>FALHA<<<"